### ISSUE TITLE
Problem installing BlockPlus - Omeka S 3.0.1

### ISSUE THREAD

**Issue by jaramberri** [Daniel-KM/Omeka-S-module-BlockPlus#1]
Problem with GitHub

<img width="635" alt="BlocPlus-gitlab-OmekaS301" src="https://user-images.githubusercontent.com/6490447/100196542-4b4cf080-2ef9-11eb-985e-f8ee36874dbb.png">

**Comment by Daniel-KM** [comment]
Your issue is strange, because the url is github in the composer file, not gitlab : https://github.com/Daniel-KM/Omeka-S-module-BlockPlus/blob/master/composer.json#L55 , so I think it's a temporary issue that should be fixed with a cleaning of the composer cache.
