### ISSUE TITLE
Windows issue: "Template to display" drop-down doesn't show templates other than Default

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-BlockPlus#2]
Even if alternative templates are loaded in view\common\block-layout of the Theme used (with the right prefix in the name), no choice is available other than Default in the drop down select of every single block.
![github 1](https://user-images.githubusercontent.com/5129066/111060047-6f2d4580-849a-11eb-82b8-264249174325.png)
![immagine](https://user-images.githubusercontent.com/5129066/111060066-96841280-849a-11eb-8536-98640831fd11.png)

**Comment by Falteri** [comment]
Solved.
Problem was related with the path format in Windows that must be 'template' => 'common\block-layout\browse-preview' instead of 'template' => 'common/block-layout/browse-preview'

**Comment by Falteri** [comment]
There is maybe something to change in filteredFilesInFolder()? It seems that the forward slashes should be the best to be used to fit both in Linux and in Windows.

**Comment by Falteri** [comment]
The problem was temporary solved adding this:
**_$layout = str_replace(array('/', '\\'), DIRECTORY_SEPARATOR, $layout);_**
as the first instruction in the function **filteredFilesInFolder()**, but it doesn't seem to be to best solution.

**Comment by Daniel-KM** [comment]
I cannot fix Windows issue, but if you have some light idea that will work in all case, it will be fine.

**Comment by Falteri** [comment]
Everything move on Linux. No light idea for Windows for now.
