### ISSUE TITLE
ReIndex problem

### ISSUE THREAD

**Issue by Falteri** [Daniel-KM/Omeka-S-module-BlockPlus#4]
Omeka S Reindexing fails for some reason related to BlockPlus module:

Fatal error: Uncaught Error: Call to a member function getParam() on null in D:\xampp\htdocs\banchedati-idi\application\src\Api\Representation\ItemRepresentation.php:90
Stack trace:
#0 D:\xampp\htdocs\banchedati-idi\modules\BlockPlus\view\common\block-layout\browse-preview-carousel.phtml(69): Omeka\Api\Representation\ItemRepresentation->siteUrl()
#1 D:\xampp\htdocs\banchedati-idi\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php(505): include('D:\\xampp\\htdocs...')
#2 D:\xampp\htdocs\banchedati-idi\vendor\laminas\laminas-view\src\Helper\Partial.php(61): Laminas\View\Renderer\PhpRenderer->render(NULL, NULL)
#3 [internal function]: Laminas\View\Helper\Partial->__invoke('common\\block-la...', Array)
#4 D:\xampp\htdocs\banchedati-idi\vendor\laminas\laminas-view\src\Renderer\PhpRenderer.php(396): call_user_func_array(Object(Laminas\View\Helper\Partial), Array)
#5 D:\xampp\htdocs\banchedati-idi\modules\BlockPlus\src\Site\BlockLayout\BrowsePreview.php(192): Laminas\View\Renderer\PhpRenderer->__call('partial', Array)
#6 D
in D:\xampp\htdocs\banchedati-idi\application\src\Api\Representation\ItemRepresentation.php on line 90

**Comment by Daniel-KM** [comment]
it will be fixed in next version of Omeka (3.1).

**Comment by Daniel-KM** [comment]
For the short time, you can get the site from the page block then set `->siteUrl($site->slug())` in the view.

**Comment by Daniel-KM** [comment]
This is fixed for now too.
