### ISSUE TITLE
ResourceText layout invalid after update to 3.3.14.1

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/Omeka-S-module-BlockPlus#5]
After updating to version 3.3.14.1, ResourceText layout is invalid. Content is still in the database, but not visible in public view nor in Omeka dashboard.

<img width="636" alt="Screen Shot 2022-02-24 at 11 54 04 AM" src="https://user-images.githubusercontent.com/6174191/155597736-a1e26d26-8707-43bc-b10d-3340cf95d763.png">

Using Omeka S version 3.1.0

**Comment by Daniel-KM** [comment]
This is related to the version of php and this is fixed in version 3.3.15.6.
