### ISSUE TITLE
D3 Graph usage

### ISSUE THREAD

**Issue by coret** [Daniel-KM/Omeka-S-module-BlockPlus#7]
I'm happy to see D3 Graph has been added to the BlockPlus module. 

I do see the D3 block in the Page Editor, but it in unclear to me how to make use of this new feature.

![image](https://user-images.githubusercontent.com/101820/195151137-2cea8ee1-a6bc-4ebf-9b3e-eef8451d61dd.png)

I guess the intented use is on Item pages? Any examples (online/code) available?

**Comment by Daniel-KM** [comment]
An example of use can be seen on the digital library of the [Fondation de la Maison de Salins](https://cooparchives.maison-salins.fr/s/fr/page/carte-heuristique).

**Comment by Daniel-KM** [comment]
The example above is added as a new template in the block.
